name: autopush

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run
        run: echo "Running scheduled job or on push"
